# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Publish Android"

on:
  release:
    types: [ published ]

jobs:
  deploy:
    if: github.repository == 'kurzacationer/sm7-personal-app'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: "Setup Flutter 3.7.3"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-
      - name: "Inject Upload JKS"
        env:
          KEY_JKS: ${{ secrets.UPLOAD_KEY_JKS }}
        run: echo $KEY_JKS | base64 -d > android/app/upload.jks
      - name: "Retrieve dependencies"
        run: flutter pub get
      - name: "Run build_runner"
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: "Build app bundle"
        env:
          KEY_PASSWORD: ${{ secrets.UPLOAD_ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
        run: flutter build appbundle --build-name=${{ github.event.release.tag_name }} --build-number=${{ github.run_number }}
      - name: "Upload Android Release to Play Store"
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: nl.kurza.test_project
          inAppUpdatePriority: 2
          status: draft
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal


