# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Flutter Test & Analyze"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: "Setup Flutter 3.7.3"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-
      - name: "Retrieve dependencies"
        run: flutter pub get
      - name: "Analyze"
        run: flutter analyze
      - name: "Test"
        run: flutter test


